apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iv510z6mw-go
  janus-idp.io/tekton: iv510z6mw-go
  backstage.io/kubernetes-id: iv510z6mw-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iv510z6mw-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
