apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iv510z6mw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iv510z6mw-go 
  name: iv510z6mw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iv510z6mw-go 
